services:
  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
  neo4j:
    image: neo4j:latest
    ports:
      - '7474:7474'
      - '7687:7687'
